create table "public"."employees" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."employees" enable row level security;

CREATE UNIQUE INDEX employees_pkey ON public.employees USING btree (id);

alter table "public"."employees" add constraint "employees_pkey" PRIMARY KEY using index "employees_pkey";


